[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "lh_core"
description = "telegram bot for lautis hannover"
#long_description = file: src/README_package.md
#long_description_content_type = text/markdown
authors = [{name = "Lautis Hannover", email = "hallo@lautis-hannover.de"}]
requires-python = ">=3.12"
dependencies = [
    "httpx >= 0.24",
    "pytz",
    "requests",
 ]
dynamic = ["version"]

[project.optional-dependencies]

[project.scripts]
lhtool = "lh_core.__main__:main"

[tool.setuptools.dynamic]
version = {attr = "lh_core.__version__"}
